# Configuration for Streamlit deployment
# For Streamlit Cloud, we'll use the default port (8501)
# For Replit, we'll use port 5000
[server]
headless = true
enableXsrfProtection = false

# Uncomment these lines for local Replit deployment
address = "0.0.0.0"
port = 5000

[theme]
# Default streamlit theme, ensuring consistent appearance
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
