# Configuration file for Streamlit Cloud deployment
[server]
headless = true
enableXsrfProtection = false

# No port specified for Streamlit Cloud (it will use default 8501)

[theme]
# Default streamlit theme, ensuring consistent appearance
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"